// <auto-generated />
using System;
using ExamHubProject.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamHubProject.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamHubProject.Models.Entities.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminID = 1,
                            AdminName = "Admin",
                            Password = "123456",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("ExamHubProject.Models.Entities.Exam", b =>
                {
                    b.Property<int>("ExamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamID"));

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdfPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<int>("RefLessonID")
                        .HasColumnType("int");

                    b.HasKey("ExamID");

                    b.HasIndex("RefLessonID");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("ExamHubProject.Models.Entities.Lesson", b =>
                {
                    b.Property<int>("LessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonID"));

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonID");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            LessonID = 1,
                            LessonName = "Türkçe"
                        },
                        new
                        {
                            LessonID = 2,
                            LessonName = "Matematik"
                        },
                        new
                        {
                            LessonID = 3,
                            LessonName = "Geometri"
                        },
                        new
                        {
                            LessonID = 4,
                            LessonName = "Biyoloji"
                        },
                        new
                        {
                            LessonID = 5,
                            LessonName = "Kimya"
                        },
                        new
                        {
                            LessonID = 6,
                            LessonName = "Fizik"
                        },
                        new
                        {
                            LessonID = 7,
                            LessonName = "Tarih"
                        },
                        new
                        {
                            LessonID = 8,
                            LessonName = "Coğrafya"
                        });
                });

            modelBuilder.Entity("ExamHubProject.Models.Entities.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ExamHubProject.Models.Entities.StudentExam", b =>
                {
                    b.Property<int>("StudentExamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentExamID"));

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExamScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RefExamID")
                        .HasColumnType("int");

                    b.Property<int>("RefStudentID")
                        .HasColumnType("int");

                    b.Property<string>("StudentAnswersJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentExamID");

                    b.HasIndex("RefExamID");

                    b.HasIndex("RefStudentID");

                    b.ToTable("StudentExams");
                });

            modelBuilder.Entity("ExamHubProject.Models.Entities.Exam", b =>
                {
                    b.HasOne("ExamHubProject.Models.Entities.Lesson", "Lesson")
                        .WithMany("Exams")
                        .HasForeignKey("RefLessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("ExamHubProject.Models.Entities.StudentExam", b =>
                {
                    b.HasOne("ExamHubProject.Models.Entities.Exam", "Exam")
                        .WithMany("StudentExams")
                        .HasForeignKey("RefExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamHubProject.Models.Entities.Student", "Student")
                        .WithMany("StudentExams")
                        .HasForeignKey("RefStudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ExamHubProject.Models.Entities.Exam", b =>
                {
                    b.Navigation("StudentExams");
                });

            modelBuilder.Entity("ExamHubProject.Models.Entities.Lesson", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("ExamHubProject.Models.Entities.Student", b =>
                {
                    b.Navigation("StudentExams");
                });
#pragma warning restore 612, 618
        }
    }
}
